#-------------------------------
# General Site Settings
title: Amir Sadeghi
description: "I’m a computational biophysicist turned applied scientist with expertise in large-scale simulations, data management and analytics, ML/AI/GenAI tools, and cloud infrastructure. I’m seeking opportunities to develop intelligent, production-grade systems that bring scientific rigor to real-world challenges across business, research, and technology."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Applied Scientist Portfolio #<span style="color:#f58506"> Portfolio </span>
location: "Ontario, Canada"
resume_url: "/assets/amirhsi_resume.pdf"
avatar_image: /img/amirhsi_avatar.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/amirhsi/" # Add your linkedln handle
github: "https://github.com/amirhs1"  # Add your github handle
google_scholar: "https://scholar.google.ca/citations?user=g6jv8aQAAAAJ&hl=en" # Add your google scholar handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: true


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
